<?php
/**
 * @version		1.0.0 oms2 $
 * @package		oms2
 * @copyright	Copyright © 2013 - All rights reserved.
 * @license		GNU/GPL
 * @author		Andrey Shlyapin
 * @author mail	andrey@skzd.ru
 * @website		http://www.pokupaem-v-amerike.com/
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

// Component Helper

jimport('joomla.application.component.helper');
jimport('joomla.html.grid');


class oms2Helper
{
	// Your custom code here
	static  $allowed_status=[0,1,2,3,4,5];
	
	static function user_name ($id=null) {
		$user = JFactory::getUser();
	}
	
	static function getStatus($status){
		if (in_array($status, self::$allowed_status)) {
			return JText::_('OMS STATUS'.$status);
		}
	}
	
	static function getAllStatus(){
		foreach (self::$allowed_status as $key) {
			$allStatus[$key]=self::getStatus($key);
		}
		return $allStatus;
	}
	
	static function getUserSelect($name,$options=FALSE,$key='value',$value='text',$default=FALSE) {
		$query = 'SELECT id AS value, username AS text FROM #__users order by username asc';
		$b=JHTML::_('list.genericordering',$query);
		return  JHTML::_('select.genericlist',$b,$name,$options,$key,$value,$default);
	}	
	static function debug($param) {
			echo "<pre>";
			print_r($param);
			echo "</pre>";
			die();;
	}
	
	static function getStatusSelect($name,$default=FALSE,$options=FALSE){
		return JHTML::_('select.genericlist', self::getAllStatus(), $name, $options, False, False, $default);
	}
}







?>