<?php
/**
 * @version		1.0.0 oms2 $
 * @package		oms2
 * @copyright	Copyright © 2013 - All rights reserved.
 * @license		GNU/GPL
 * @author		Andrey Shlyapin
 * @author mail	andrey@skzd.ru
 * @website		http://www.pokupaem-v-amerike.com/
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access

defined('_JEXEC') or die('Restricted access');

jimport('joomla.application.component.controller');


class oms2Controller extends JController
{
	/**
	 * Custom Constructor
	 */
	
	
	function __construct()
	{
		parent::__construct();
	}
	
	public function display($cachable = false, $urlparams = false)
	{
		
		$woView=array('addOrder','saveorder','addpay','pconfirm','filter', 'deleteorder','setstatus');
		$adminGroup='10';
		
		$document = JFactory::getDocument();
		$document->addStyleSheet(JURI::root(true) . '/components/com_oms2/assets/css/style.css');
		$document->addStyleSheet("http://fonts.googleapis.com/css?family=Scada&subset=latin,cyrillic");
		$session = JFactory::getSession();
		$vName	 = JRequest::getCmd('task', 'userorders');
		$vFormat = $document->getType();
		$lName	 = JRequest::getCmd('layout', 'default');
		
		
		$user = JFactory::getUser();
		if ($user->get('id') == 0) {
			$this->setRedirect('index.php', 'Not allowed');
			return;
		}
		if (in_array($adminGroup, array_keys($user->groups))) {
			$user->omsadmin = true;
		} else {
			$user->omsadmin = false;
		}
		
		$model = $this->getModel('Oms2');
		
		
		
		if ( !in_array($vName, $woView)){
				if ($view = $this->getView($vName, $vFormat)) {
					// Do any specific processing by view.
					$model->admin=$user->omsadmin;
					$view->setModel($model, true);
					$view->setLayout($lName);
					$view->assignRef('document', $document);
					$view->display();
			}
		}else{
			switch ($vName){
				case 'filter':
					JRequest::checkToken() or jexit('Invalid Token');
					$postData=JRequest::get('POST');
					foreach ($postData as $key => $value) {
						if (strpos($key, 'order-filter') === 0 or $key=='oms-user'){
							$orderFilter[$key]=$value;
						} 
					}
					$sessionData = $session->get('orderFilter');
					if(!isset($postData['order-filter-status']) and isset($sessionData['order-filter-status'])) {
						$orderFilter['order-filter-status']=$sessionData['order-filter-status'];
					}
					if(!isset($postData['order-filter-status']) and !isset($sessionData['order-filter-status'])) {
						$orderFilter['order-filter-status']=array(1,1);
					}
					$session->set('orderFilter',$orderFilter);
					$this->setRedirect('index.php?option=com_oms2', 'FILTER SET');
					break;
				case 'addpay':
					JRequest::checkToken() or jexit('Invalid Token');
					$message = $model->addPay();
					$this->setRedirect('index.php?option=com_oms2', $message);
					break;
				case 'deleteorder':
						if (!$user->omsadmin){
							$this->setRedirect('index.php?option=com_oms2', 'Not allowed');
							break;
						}
						$message= $model->deleteOrder();
						$this->setRedirect('index.php?option=com_oms2', $message);
						break;
				case 'saveorder':
					if (!$user->omsadmin){
						$this->setRedirect('index.php?option=com_oms2', 'Not allowed');
						break;
					}
					JRequest::checkToken() or jexit('Invalid Token');
					$message= $model->saveOrder();
					$this->setRedirect('index.php?option=com_oms2&view=order&id='.JRequest::getCmd('id'), $message);
					break;
				case 'pconfirm':
					if (!$user->omsadmin){
						$this->setRedirect('index.php?option=com_oms2', 'Not allowed');
						break;
					}
					$message=$model->paymentConfirm();
					$this->setRedirect('index.php?option=com_oms2&view=payments', $message);
					break;
				case 'addOrder':
					JRequest::checkToken() or jexit('Invalid Token');
					$message=$model->addOrder();
					$this->setRedirect('index.php?option=com_oms2&view=order&id='.$model->row->id, $message);
					break;
				case 'setstatus':
						$message=$model->setOrderStatus();
						$this->setRedirect('index.php?option=com_oms2', $message);
						break;
				default:
					$this->setRedirect('index.php?option=com_oms2', FALSE);
			}			
		}
	}

}
?>