<?php
/**
 * @version		1.0.0 oms2 $
 * @package		oms2
 * @copyright	Copyright © 2013 - All rights reserved.
 * @license		GNU/GPL
 * @author		Andrey Shlyapin
 * @author mail	andrey@skzd.ru
 * @website		http://www.pokupaem-v-amerike.com/
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

jimport('joomla.application.component.controller');


class oms2Controller extends JController
{
	/**
	 * Custom Constructor
	 */
	
	
	function __construct()
	{
		parent::__construct();
	}
	
	public function display($cachable = false, $urlparams = false)
	{
		
		$woView=array('addOrder','saveorder','addpay','pconfirm','filter');
		$adminGroup='9';
		
		$document	= JFactory::getDocument();
		$document->addStyleSheet(JURI::root(true) . '/components/com_oms2/assets/css/style.css');
		
		$session = JFactory::getSession();
		
		$vName	 = JRequest::getCmd('task', 'userorders');
		$vFormat = $document->getType();
		$lName	 = JRequest::getCmd('layout', 'default');
		
		
		$user = JFactory::getUser();
		if ($user->get('id') == 0) die('Restricted access');
		if (in_array($adminGroup, array_keys($user->groups))) $admin = true;
		#oms2Helper::debug(array_keys($user->groups));
		
		if ( !in_array($vName, $woView)){
				if ($view = $this->getView($vName, $vFormat)) {
					// Do any specific processing by view.
					switch ($vName) {
						case 'add':
							$model = $this->getModel('Oms2');
							break;
						default:
							$model = $this->getModel('Oms2');
							break;
					}
			
					$view->setModel($model, true);
					$view->setLayout($lName);
					$view->assignRef('document', $document);
					$view->display();
			}
		}else{
			switch ($vName){
				case 'filter':
					JRequest::checkToken() or jexit('Invalid Token');
					$model = $this->getModel('Oms2');
					foreach (JRequest::get('POST') as $key => $value) {
						if (strpos($key, 'order-filter') === 0){
							$orderFilter[$key]=$value;
						} 
					}
					
					$session->set('orderFilter',$orderFilter);
					$this->setRedirect('index.php?option=com_oms2', 'FILTER SET');
					break;
				case 'addpay':
					JRequest::checkToken() or jexit('Invalid Token');
					$model = $this->getModel('Oms2');
					$message = $model->addPay();
					$this->setRedirect('index.php?option=com_oms2', $message);
					break;
				case 'saveorder':
					if (!$admin){
						$this->setRedirect('index.php?option=com_oms2', 'Not allowed');
						break;
					}
					JRequest::checkToken() or jexit('Invalid Token');
					$model = $this->getModel('Oms2');
					$message= $model->saveOrder();
					if($model->update_status) $message.= '. History - '.$model->addHistory(JRequest::getCmd('id'),JRequest::getCmd('order-status'));
					$this->setRedirect('index.php?option=com_oms2&view=order&id='.JRequest::getCmd('id'), $message);
					break;
				case 'pconfirm':
					if (!$admin){
						$this->setRedirect('index.php?option=com_oms2', 'Not allowed');
						break;
					}
					$model = $this->getModel('Oms2');
					$message=$model->paymentConfirm();
					$this->setRedirect('index.php?option=com_oms2&view=payments', $message);
					break;
				case 'addOrder':
					JRequest::checkToken() or jexit('Invalid Token');
					$model = $this->getModel('Oms2');
					$message=$model->addOrder(JRequest::get('post'));
					$insertId=$model->getInsertId();
					$message.='. History - '.$model->addHistory($insertId);
					$this->setRedirect('index.php?option=com_oms2&view=order&id='.$insertId, $message);
					
					break;
				default:
					$this->setRedirect('index.php?option=com_oms2', FALSE);
			}			
		}
	}




}
?>