<?php
/**
 * @version		1.0.0 oms2 $
 * @package		oms2
 * @copyright	Copyright © 2013 - All rights reserved.
 * @license		GNU/GPL
 * @author		Andrey Shlyapin
 * @author mail	andrey@skzd.ru
 * @website		http://www.pokupaem-v-amerike.com/
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

// Your custom code here
$order=$this->Order;
$History=$this->History;
$order->status_text=oms2Helper::getStatus($order->status);

?>

<div id="oms-container">


	<?php require_once (JPATH_COMPONENT.DS.'views'.DS.'tmpl'.DS.'topmenu.php');?>
<div id="order-view-container">
    <div id="order-first-row">
    	<div class="cell"><?php echo $order->time;?></div>
    	<div class="cell"><?php echo JHtml::link($order->item_url,$order->site,array('target'=>'_blank'));?></div>
    	<?php $user=JFactory::getUser($order->user_id);?>
    	<div id="name" class="cell  order-top-menu">
			<span class="name header"><?php echo $user->name; ?>(<?php echo $user->username; ?>)</span>
		</div>
		<?php if ($this->OmsUser->user-omsadmin) {?>
    	<div class="cell">
    		<?php echo JHtml::link("index.php?option=com_oms2&task=editorder&id=".$order->id,'Изменить');?>
    	</div>
    	<?php }?>
    </div >
    <div id=order-item><h1><?php echo $order->item;?></h1></div>
    <div id="order-second-row"> 
    	<div id="order-image" class="cell">
    		<?php if($order->image=='') $order->image='noimage.jpg';?>
    		<a rel="rokbox" href="<?php echo JURI::root(true) . '/components/com_oms2/assets/images/orders/'.$order->image;?>"><img id="order-image" alt="Фото" width=100 height=100 src="<?php echo JURI::root(true) . '/components/com_oms2/assets/images/orders/'.$order->image;?>"></a>
    	</div>
    	<div id="order-params"  class="cell">
    		<ul>
    			<li><span>Артикул:</span> <?php echo $order->article;?></li>
    			<li><span>Размер:</span> <?php echo $order->size;?></li>
    			<li><span>Цвет: </span><?php echo $order->color;?></li>
    		</ul>
    	</div>
    	<div id="order-amount"  class="cell"><span>Кол-во</span><br><?php echo $order->amount;?></div>
    	<div id="order-price"  class="cell"><span>Цена</span><br><?php echo $order->price;?> <?php echo $order->currency;?></div>
    	<div id="order-costs"  class="cell">
    		<ul style="vertical-align: top;">
    			<li><span>Налог:</span> <?php echo $order->tax;?>%</li>
    			<li><span>Коммисия:</span> <?php echo $order->interest;?>%</li>
    			<li><span>Курс:</span> <?php echo $order->currency_rate;?> (<?php echo $order->currency?>)</li>
    		</ul>
    	</div>
    	<div id="order-total"  class="cell"><span>Итого</span><br><?php echo $order->total;?> руб.</div>
    	<div id="order-status"  class="cell"><span>Статус</span><br><div class="status <?php echo 'status'.$order->status;?>"><?php echo $order->status_text;?></div></div>
    </div>
    <div id="order-notes-header"><h2>Комментарий</h2></div>
    <div id="order-notes"><h3><?php echo $order->notes;?></h3></div>
</div>
<div id="history-container">
<?php 
foreach ($History as $event){
	?>
	<div id="history-row">
		<div  id="history-event-date" class="cell">
		<?php echo $event->date;?>
		</div> 
		<div  id="history-event-message" class="cell">Изменен статус. Текущий статус: </div>
		<div id="history-event-status" class="cell status<?php echo $event->status;?>">
		<?php echo oms2Helper::getStatus($event->status);?>
		</div>
	</div>	
<?php }?>
</div>
</div>