<?php
/**
 * @version		1.0.0 oms2 $
 * @package		oms2
 * @copyright	Copyright © 2013 - All rights reserved.
 * @license		GNU/GPL
 * @author		Andrey Shlyapin
 * @author mail	andrey@skzd.ru
 * @website		http://www.pokupaem-v-amerike.com/
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

// Your custom code here
$order=$this->Order;
$History=$this->History;
?>

<div id="oms-container">
<div id="order-container">

	<?php require_once (JPATH_COMPONENT.DS.'views'.DS.'tmpl'.DS.'topmenu.php');?>

    <div id="order-first-row">
    	<div><?php echo $order->time;?></div>
    	<div><?php echo $order->site;?></div>
    	<div>
    		<?php echo JHtml::link($order->item_url,'Ссылка',array('target'=>'_blank'));?>
    		<?php echo JHtml::link("index.php?option=com_oms2&task=editorder&id=".$order->id,'Изменить');?>
    	</div>
    </div>
    <div id=order-item><h1><?php echo $order->item;?></h1></div>
    <div>
    	<div id="order-image">
    		<?php if($order->image=='') $order->image='noimage.jpg';?>
    		<a rel="rokbox" href="<?php echo JURI::root(true) . '/components/com_oms2/assets/images/orders/'.$order->image;?>"><img alt="Фото" width=100 height=100 src="<?php echo JURI::root(true) . '/components/com_oms2/assets/images/orders/'.$order->image;?>"></a>
    	</div>
    	<div id="order-params">
    		<ul>
    			<li>Артикул: <?php echo $order->article;?></li>
    			<li>Размер: <?php echo $order->size;?></li>
    			<li>Цвет: <?php echo $order->color;?></li>
    		</ul>
    	</div>
    	<div id="order-amount"><?php echo $order->amount;?></div>
    	<div id="order-price"><?php echo $order->price;?></div>
    	<div id="order-costs">
    		<ul style="vertical-align: top;">
    			<li>Налог: <?php echo $order->tax;?>%</li>
    			<li>Коммисия: <?php echo $order->interest;?>%</li>
    			<li>Курс: <?php echo $order->currency_rate;?> (<?php echo $order->currency?>)</li>
    		</ul>
    	</div>
    	<div id="order-total"><?php echo $order->total;?></div>
    </div>
    <div id="order-notes-header">Комментарий</div>
    <div id="order-notes"><h3><?php echo $order->notes;?></h3></div>
</div>
<div id="history-container">
<?php 
foreach ($History as $event){
	?>
	<div id="history-row">
		<div  id="history-event-date">
		<?php echo $event->date;?>
		</div> 
		<div id="history-event-date">
		Изменен статус. Текущий статус: <?php echo $event->status;?>
		</div>
	</div>	
<?php }?>
</div>
</div>