<?php
/**
 * @version		1.0.0 oms2 $
 * @package		oms2
 * @copyright	Copyright © 2013 - All rights reserved.
 * @license		GNU/GPL
 * @author		Andrey Shlyapin
 * @author mail	andrey@skzd.ru
 * @website		http://www.pokupaem-v-amerike.com/
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

// Your custom code here
$order=$this->Order;
#oms2Helper::debug($order);

?>

<div style="overflow:hidden;" id="order-container">
	
    <div style="background: #fd0">
    	<div style="float:left; width:40%;"><?php echo $order->time;?></div>
    	<div style="float:left; width:40%;"><?php echo $order->site;?></div>
    	<div style="overflow:hidden;">
    		<?php echo JHtml::link($order->item_url,'Ссылка',array('target'=>'_blank'));?>
    		<?php echo JHtml::link("index.php?option=com_oms2&view=editorder&id=".$order->id,'Изменить');?>
    	</div>
    </div>
    <div style=""><h1><?php echo $order->item;?></h1></div>
    <div style="height=300px;overflow:hidden;">
    	<div style="float:left; width:15%; height:100px;">Фото</div>
    	<div style="float:left; width:33%; height:100px;">
    		<ul>
    			<li>Артикул: <?php echo $order->article;?></li>
    			<li>Размер: <?php echo $order->size;?></li>
    			<li>Цвет: <?php echo $order->color;?></li>
    		</ul>
    	</div>
    	<div style="float:left; width:7%; height:100px;"><?php echo $order->amount;?></div>
    	<div style="float:left; width:10%; height:100px;"><?php echo $order->price;?></div>
    	<div style="float:left; width:20%; height:100px;">
    		<ul style="vertical-align: top;">
    			<li>Налог: <?php echo $order->tax;?>%</li>
    			<li>Коммисия: <?php echo $order->interest;?>%</li>
    			<li>Курс: <?php echo $order->currency_rate;?> (<?php echo $order->currency?>)</li>
    		</ul>
    	</div>
    	<div style="float:left; width:10%; height:100px;"><?php echo $order->total;?></div>
    </div>
    <div style="">Комментарий</div>
    <div style=""><h3><?php echo $order->notes;?></h3></div>
</div>