<?php
/**
 * @version		1.0.0 oms2 $
 * @package		oms2
 * @copyright	Copyright © 2013 - All rights reserved.
 * @license		GNU/GPL
 * @author		Andrey Shlyapin
 * @author mail	andrey@skzd.ru
 * @website		http://www.pokupaem-v-amerike.com/
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

// Your custom code here
$order=$this->Order;

?>


<form action="index.php?option=com_oms2&task=addOrder" method="post" name="adminForm" id="adminForm" enctype="multipart/form-data" >
<div id="oms-container" >

	

<?php require_once (JPATH_COMPONENT.DS.'views'.DS.'tmpl'.DS.'topmenu.php');?>
<div id="order-container" >
    <div id="new-order-first-row">
    	<div id="order-item" >
    		<span>Наименование</span>
    		<input id="order-item" size="50" name="order-item" value="<?php echo $order->item;?>">
    	</div>
    	<div id="order-url">
    		<span>Ссылка</span>
    		<input id="order-url" size="50" name="order-url" value="<?php echo $order->item_url;?>">
    	</div>
    </div>
    <div id="new-order-second-row">
    	<div id="order-article" class="cell">
			Артикул 
    		<input id="order-article" size="10" name="order-article" value="<?php echo $order->article;?>">
    	</div>
    	<div id="order-size" class="cell">
    		Размер
    		<input id="order-size" size="4" name="order-size" value="<?php echo $order->size;?>">
    	</div>
    	<div id="order-color" class="cell">
    		Цвет
    		<input id="order-color" size="10" name="order-color" value="<?php echo $order->color;?>">
    	</div>
    	<div id="order-amount" class="cell">
    		Кол-во
    		<input id="order-amount" name="order-amount" size="3" value="<?php echo $order->amount;?>">
    	</div>
    	<div id="order-price" class="cell">
    		Цена
    		<input id="order-price" name="order-price" size="5" value="<?php echo $order->price;?>">
    	</div>
    	<div id="order-currency" class="cell">
    		Валюта
    		<?php echo oms2Helper::getCurrencySelect("order-currency",$order->currency);?>
    	</div>
    	
    </div>
    <div id="order-notes">
    	<span>Комментарий</span>
    	<input id="item-form" size="50" name="order-notes" value="<?php echo $order->notes;?>">
    </div>
    <div id="order-notes">
    	Изображение
    	<?php echo $order->image;?> <input id="photo-image" size="50" name="order-image" type="file" >
    </div>
</div>
</div>
	<input id="form-submit" type="submit">
	<input type="hidden" name="option" value="com_oms2" />
	<input type="hidden" name="task" value="addOrder" />
	<?php echo JHTML::_('form.token'); ?>
</form>