<?php
/**
 * @version		1.0.0 oms2 $
 * @package		oms2
 * @copyright	Copyright © 2013 - All rights reserved.
 * @license		GNU/GPL
 * @author		Andrey Shlyapin
 * @author mail	andrey@skzd.ru
 * @website		http://www.pokupaem-v-amerike.com/
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');
?>
<div id="order-container" style="overflow:hidden;">
	<?php require_once (JPATH_COMPONENT.DS.'views'.DS.'tmpl'.DS.'topmenu.php');?>
	
	<div id="order-tablebody" style="overflow:hidden;">
<?php 		
foreach ($this->OmsUser->payments as $key=>$payment) {
	echo "<div id=\"row-order\" style=\"overflow:hidden;\">";
	echo "<div style=\"float:left; overflow: hidden; width: 24%;\">".$payment->payment_date."</div>";
	echo "<div style=\"float:left; overflow: hidden; width: 24%;\">".$payment->value."</div>";
	echo "<div style=\"float:left; overflow: hidden; width: 24%;\">".$payment->notes."</div>";
	echo "<div style=\"float:left; overflow: hidden; width: 24%;\">".$payment->status;
	if ($payment->status != 1){
		echo '<a href="index.php?option=com_oms2&task=pconfirm&id='.$payment->id.'">Подтвердить	</a>';
	}
	echo "</div></div>";
}
 ?>	
	</div>
</div>

