<?php
/**
 * @version		1.0.0 oms2 $
 * @package		oms2
 * @copyright	Copyright © 2013 - All rights reserved.
 * @license		GNU/GPL
 * @author		Andrey Shlyapin
 * @author mail	andrey@skzd.ru
 * @website		http://www.pokupaem-v-amerike.com/
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

// Your custom code here
foreach ($this->orders as $key=>$order) {
	
	unset($order->item_url);
	unset($order->id);
	$this->orders[$key]=$order;
}

$table2=new oms2HtmlTable;
$table2->addTable($this->orders,array('header'=>0,'footer'=>-1));
echo $table2->toString();
?>