<?php
/**
 * @version		1.0.0 oms2 $
 * @package		oms2
 * @copyright	Copyright © 2013 - All rights reserved.
 * @license		GNU/GPL
 * @author		Andrey Shlyapin
 * @author mail	andrey@skzd.ru
 * @website		http://www.pokupaem-v-amerike.com/
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

// Your custom code here
foreach ($this->orders as $key=>$order) {
	$order->time=substr($order->time, 0,10);
	$order->item=JHtml::link($order->item_url,$order->item.' ('.$order->site.')');
	$order->status=oms2Helper::getStatus($order->status);	
	$this->orders[$key]=$order;
}

$table2=new oms2HtmlTable;
$table2->allow_columns=array('item','time','status');

$table2->addTable($this->orders,array('header'=>0,'footer'=>-1));
oms2Helper::debug($this);
echo $table2->toString();
?>