<?php
/**
 * @version		1.0.0 oms2 $
 * @package		oms2
 * @copyright	Copyright © 2013 - All rights reserved.
 * @license		GNU/GPL
 * @author		Andrey Shlyapin
 * @author mail	andrey@skzd.ru
 * @website		http://www.pokupaem-v-amerike.com/
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');
?>
<div id="oms-container">
	<?php require_once (JPATH_COMPONENT.DS.'views'.DS.'tmpl'.DS.'topmenu.php');?>
	<div id="table-container" style="overflow:hidden;">
	<div id="filter-container">
		<form action="index.php?option=com_oms2&task=filter" method="post" id="adminForm" name="adminForm">	
			<?php if($this->OmsUser->user->omsadmin) {?>
			<div class="filter-element oms-user">
			<?php 
			echo oms2Helper::getUserSelect('oms-user',array('onchange'=>'Joomla.submitbutton(\'filter\')'),$this->orderFilter['oms-user']);
			?>
			</div>
			<?php }?>
			<div class="filter-element">
			<?php 
			echo JHTML::calendar($this->orderFilter['order-filter-date'],'order-filter-date','order-filter-date','%Y-%m-%d',array('size'=>'6','onchange'=>'Joomla.submitbutton(\'filter\')'));
			?>
			</div>
			<div class="filter-element">
			<?php 
			echo oms2Helper::getCheckList($this->orderFilter['order-filter-status'], 'order-filter-status',"onchange=\"Joomla.submitbutton('filter')\"");
			?>
			</div>
			<input type="hidden" name="option" value="com_oms2" />
			<input type="hidden" name="task" value="order-filter" />
			<?php echo JHTML::_('form.token'); ?>
		</form>
	</div>
	<div id="data-container">
<?php 		
if (count($this->OmsUser->orders)<=0){
	?><div id="row-order">Нет подходящих заказов. Измените условия фильтров</div><?php
}
foreach ($this->OmsUser->orders as $key=>$order) {
	$order->status_text=oms2Helper::getStatus($order->status);
	$this->orders[$key]=$order;
	$copylink=JHtml::link('index.php?option=com_oms2&task=neworder&id='.$order->id,'Копировать');
?>
	<div id="row-order">
		<div class="cell">
			<span class="date"><?php echo JHtml::link('index.php?option=com_oms2&task=order&id='.$order->id,substr($order->time, 0,10));?></span>
		</div>
		<div class="cell">
		<?php
		foreach (oms2Helper::getAllStatus() as $key) {
			if ($key['value']<$order->status) {
				$class='passed';
			} elseif ($key['value']>$order->status) {
				$class='notpassed';
			} else {
				$class='status'.$order->status;
			}
			if ($key['value']>$order->status and $this->OmsUser->user->omsadmin) {
				$onclick='onClick="javascript: if (confirm(\'Изменить статус?\')) { window.location=\'index.php?option=com_oms2&task=setstatus&order-status='.$key['value'].'&id='.$order->id.'\'; void(\'\') } else { void(\'\') };"';
			} else {
				$onclick='';
			} 
			?>	
			<div title="<?php echo $key['text']?>" <?php echo $onclick;?> class="statusbar <?php echo $class;?>"></div>
			<?php 
		}
		?>
		</div>
		<div class="cell">
			<span class="url"><?php echo JHtml::link($order->item_url,$order->site,array('target'=>'_blank','title'=>'Просмотреть заказ на сайте магазина'));?></span>
		</div>
		<?php if($this->OmsUser->user->omsadmin) {?>
		<div class="cell">
			<span class="copy"><a  title="Копировать заказ" href="index.php?option=com_oms2&task=neworder&id=<?php echo $order->id;?>">Копировать</a></span>			
			<span class="delete"><a title="Удалить заказ" href="index.php?option=com_oms2&task=deleteorder&id=<?php echo $order->id;?>">Удалить</a></span>
			<span class="edit"><a title="Изменить заказ" href="index.php?option=com_oms2&task=editorder&id=<?php echo $order->id;?>">Изменить</a></span>
		</div>
		<?php }?>
		<div class="clear"></div>
		<div class="cell" id="order-item">
			<div class="cell" id="order-image">
				<?php if($order->image=='') $order->image='noimage.jpg';?>
				<a rel="rokbox" href="<?php echo JURI::root(true) . '/components/com_oms2/assets/images/orders/'.$order->image;?>">
					<img  id="order-image" alt="Фото" src="<?php echo JURI::root(true) . '/components/com_oms2/assets/images/orders/'.$order->image;?>">
				</a>
			</div>
			<span class="item"><?php echo JHtml::link('index.php?option=com_oms2&task=order&id='.$order->id,$order->item);?></span>
		</div>
		<div id="amount" class="cell">
			<span class="amount header">Кол-во</span><br>
			<span class="amount"><?php echo $order->amount;?></span>
		</div>
		<div id="price" class="cell">
			<span class="price header">Цена</span><br>
			<span class="price"><?php echo $order->price; ?></span>
		</div>
		<div id="status" class="cell">
			<span class="status header">Статус</span><br>
			<span class="status"><?php echo $order->status_text; ?></span>
		</div>
		<?php $user=JFactory::getUser($order->user_id);?>
		<div id="name" class="cell">
			<span class="name header">Логин</span><br>
			<span class="name"><?php echo $user->name; ?></span>
		</div>
		<div id="username" class="cell">
			<span class="username header">Имя</span><br>
			<span class="username"><?php echo $user->username; ?></span>
		</div>
		
	</div>
	<div class="clear"></div>
<?php 
}
 ?>	
	</div>
	</div>
</div>

