<?php
/**
 * @version		1.0.0 oms2 $
 * @package		oms2
 * @copyright	Copyright © 2013 - All rights reserved.
 * @license		GNU/GPL
 * @author		Andrey Shlyapin
 * @author mail	andrey@skzd.ru
 * @website		http://www.pokupaem-v-amerike.com/
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');
?>
<div id="order-container" style="overflow:hidden;">
	<div id="top-row"  style="overflow:hidden;">
		<div style="float:left;">Ваш баланс: <?php echo $this->OmsUser->paymentsByStatus[1]-$this->OmsUser->ordersSum;?> руб.</div>
		<div style="float:left;">
			<a href="index.php?option=com_oms2&view=payments">
			<?php 
			if($this->OmsUser->paymentsByStatus[0] != 0) {
				echo 'Не потвержденых платежей: '.$this->OmsUser->paymentsByStatus[0].' руб.';
 			} else {
				echo 'Платежи';
			}
			?>
			</a>
		</div>
		<div style="float:left;"><a href="index.php?option=com_oms2&view=neworder">Внести заказ</a></div>
		<div style="float:left;"><a href="index.php?option=com_oms2&view=newpay">Внести платеж</a></div>
	</div>
	<div id="table=body" style="overflow:hidden;">
<?php 		
foreach ($this->OmsUser->orders as $key=>$order) {
	echo "<div id=\"row-order\" style=\"overflow:hidden;\">";
	$order->time=JHtml::link('index.php?option=com_oms2&view=order&id='.$order->id,substr($order->time, 0,10));
	$order->item=JHtml::link('index.php?option=com_oms2&view=order&id='.$order->id,$order->item);
	$order->site='<span class="url"> ('.JHtml::link($order->item_url,$order->site,array('target'=>'_blank')).')</span>';
	$order->status_text=oms2Helper::getStatus($order->status);
	$this->orders[$key]=$order;
	echo '<div style="float:left; overflow: hidden; width: 10%;">'.$order->time.'</div>';
	echo '<div style="float:left; overflow: hidden; width: 40%;">'.$order->item.'</div>';
	echo '<div style="float:left; overflow: hidden; width: 25%;">'.$order->site.'</div>';
	echo '<div style="float:left; overflow: hidden; width: 10%;">'.$order->amount.'</div>';
	echo '<div style="float:left; overflow: hidden; width: 10%;">status'.$order->status.'</div>';
	echo '</div>';
}
 ?>	
	</div>
</div>

