<?php
/**
 * @version		1.0.0 oms2 $
 * @package		oms2
 * @copyright	Copyright © 2013 - All rights reserved.
 * @license		GNU/GPL
 * @author		Andrey Shlyapin
 * @author mail	andrey@skzd.ru
 * @website		http://www.pokupaem-v-amerike.com/
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

// Your custom code here
$order=$this->Order;


?>
<form action="index.php?option=com_oms2&task=saveorder&id=<?php echo $order->id;?>" method="post" name="adminForm" id="adminForm"  enctype="multipart/form-data" >

<div id="oms-container">
	<?php require_once (JPATH_COMPONENT.DS.'views'.DS.'tmpl'.DS.'topmenu.php');?>
    
    <div id="order-container">
    <div id="edit-order-first-row">
    	<div id="order-item">
    		<span>Наименование</span>
    		<input id="item" name="item" value="<?php echo $order->item;?>">
    	</div>
    	<div id="order-url">
    		<span>Ссылка</span>
    		<input id="item-url" name="item-url" value="<?php echo $order->item_url;?>">
    	</div>
    	
    </div>
    <div id="edit-order-second-row">
    	<div id="order-article" class="cell">
    		Артикул 
    		<input id="order-article" size="10" name="order-article" value="<?php echo $order->article;?>">
    	</div>
    	<div id="order-size" class="cell">
    		Размер
    		<input id="order-size" size="4" name="order-size" value="<?php echo $order->size;?>">
    	</div>
    	<div id="order-color" class="cell">
    		Цвет
    		<input id="order-color" size="10" name="order-color" value="<?php echo $order->color;?>">
    	</div>
    	<div id="order-amount" class="cell">
    		Кол-во
    		<input id="order-amount" name="order-amount" size="3" value="<?php echo $order->amount;?>">
    	</div>
    	<div id="order-price" class="cell">
    		Цена
    		<input id="order-price" name="order-price" size="5" value="<?php echo $order->price;?>">
    	</div>
    	<div id="order-currecy" class="cell">
    		Валюта
    		<?php echo oms2Helper::getCurrencySelect("order-currency",$order->currency);?>
    	</div>
    	<div class="clear"></div>
    	<div id="order-currecy-rate" class="cell">
    		Курс
    		<input id="order-currecy-rate" name="order-currency-rate" size="5" value="<?php echo $order->currency_rate;?>">
    	</div>
    	<div id="order-tax" class="cell">
    		Налог
    		<input id="order-tax" name="order-tax" size="5" value="<?php echo $order->tax;?>">
    	</div>
    	<div id="order-interest" class="cell">
    		Коммисия	
    		<input id="order-interest" name="order-interest" size="5" value="<?php echo $order->interest;?>">
    	</div>
    	<div id="status" class="cell">
    		Статус
    		<?php echo oms2Helper::getStatusSelect('order-status',$order->status,$order->status);?>
    	</div>
    </div>
    
    <div id="order-notes"><span>Комментарий</span>
    	<input id="order-notes" size="50" name="order-notes" value="<?php echo $order->notes;?>">
    </div>
    <div id="row-order-image">
    	Фото
    	<input id="order-image" size="50" name="order-image" type="file" >
    </div>
    <input id="form-submit" type="submit">
</div>
</div>
	<input type="hidden" name="option" value="com_oms2" />
	<input type="hidden" name="id" value="<?php echo $order->id;?>" />
	<input type="hidden" name="task" value="saveorder" />
	<?php echo JHTML::_('form.token'); ?>

</form>