<?php
/**
 * @version		1.0.0 oms2 $
 * @package		oms2
 * @copyright	Copyright © 2013 - All rights reserved.
 * @license		GNU/GPL
 * @author		Andrey Shlyapin
 * @author mail	andrey@skzd.ru
 * @website		http://www.pokupaem-v-amerike.com/
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');
?>
<div id="order-container" style="overflow:hidden;">
	<?php require_once (JPATH_COMPONENT.DS.'views'.DS.'tmpl'.DS.'topmenu.php');?>
	<div id="table-body" style="overflow:hidden;">
	<div id="filter-body">
		<form action="index.php?option=com_oms2&task=filter" method="post" id="adminForm" name="adminForm">	
			<div class="filter-element">
			<?php 
			echo oms2Helper::getUserSelect('oms-user',array('onchange'=>'Joomla.submitbutton(\'filter\')'),$this->orderFilter['oms-user']);
			?>
			</div>
			<div class="filter-element">
			<?php 
			echo JHTML::calendar($this->orderFilter['order-filter-date'],'order-filter-date','order-filter-date','%Y-%m-%d',array('size'=>'6','onchange'=>'Joomla.submitbutton(\'filter\')'));
			?>
			</div>
			<div class="filter-element">
			<?php 
			echo oms2Helper::getCheckList($this->orderFilter['order-filter-status'], 'order-filter-status',"onchange=\"Joomla.submitbutton('filter')\"");
			?>
			</div>
			<input type="hidden" name="option" value="com_oms2" />
			<input type="hidden" name="task" value="order-filter" />
			<?php echo JHTML::_('form.token'); ?>
		</form>
	</div>
	<div id="table-body">
<?php 		
if (count($this->OmsUser->deliverys)<=0){
	?><div id="row-order">Нет подходящих заказов. Измените условия фильтров</div><?php
}
foreach ($this->OmsUser->deliverys as $key=>$row) {
	?>
	<div id="row-oms">
			
			
			<?php
			if ($this->OmsUser->user->omsadmin and $row->user_id!=$this->OmsUser->user->id) {
				$url = "index.php?option=com_oms2&delivery=$row->date&user_id=$row->user_id";
			}else{
				$url = "index.php?option=com_oms2&delivery=$row->date";
			} 
			?>
			<div class="cell delivery">Доставка<br><?php echo $row->date;?></div>
			<div class="cell user">Пользователь<br><?php echo $row->user_id;?></div>
			<div class="cell price">Цена досткаки<br><?php echo $row->price;?></div>
			<div class="cell weight">Вес<br><?php echo $row->weight;?></div>
			<div class="cell">
				<span class="item"><a  title="Просмотреть заказы" href="<?php echo $url;?>">Заказы</a></span>			
				<br>
				<span class="delete"><a title="Изменить доставка" href="">Изменить</a></span>
			</div>
			<div class="clear"></div>
		</div>
<?php 
}
 ?>	
	</div>
	</div>
</div>

