<?php
/**
 * @version		1.0.0 oms2 $
 * @package		oms2
 * @copyright	Copyright © 2013 - All rights reserved.
 * @license		GNU/GPL
 * @author		Andrey Shlyapin
 * @author mail	andrey@skzd.ru
 * @website		http://www.pokupaem-v-amerike.com/
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

// Your custom code here
?>

<div id="oms-container">


	<?php require_once (JPATH_COMPONENT.DS.'views'.DS.'tmpl'.DS.'topmenu.php');?>
<div id="payment-container">
<form action="index.php?option=com_oms2&task=addpay" method="post" name="adminForm" id="adminForm">
<div id="payment-date" class="cell">
    		<h3>Дата платежа</h3>
			<?php 
				echo JHTML::calendar(date('Y-m-d'),'payment_date','payment_date','%Y-%m-%d');
			?>
    </div>
    <div id="payment-value" class="cell">
    		<h3>Сумма</h3>
    		<input id="payment-value" name="payment-value">
    </div>
    <div id="paymeny-notes" class="cell">
    		<h3>Комментарий</h3>
    		<input id="payment-notes" size="50" name="payment-notes">
    </div>
    <div class="clear"></div>
    <input id="form-submit" type="submit">
	<input type="hidden" name="option" value="com_oms2" />
	<input type="hidden" name="task" value="addpay" />
	<?php echo JHTML::_('form.token'); ?>
    </form>
</div>
</div>
