<?php
/**
 * @version		1.0.0 oms2 $
 * @package		oms2
 * @copyright	Copyright © 2013 - All rights reserved.
 * @license		GNU/GPL
 * @author		Andrey Shlyapin
 * @author mail	andrey@skzd.ru
 * @website		http://www.pokupaem-v-amerike.com/
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

// Your custom code here

?>
<form action="index.php?option=com_oms2&view=addpay" method="post" name="adminForm" id="adminForm">
<div style="overflow:hidden;" id="order-container">
    	<div style="float: left; overflow:hidden;" id="payment-date">
    		<h3>Дата платежа</h3>
<?php 
echo JHTML::calendar(date('Y-m-d'),'payment_date','payment_date','%Y-%m-%d');
?>
    	</div>
    	<div style="float: left; overflow:hidden;" id="payment-value">
    		<h3>Сумма</h3>
    		<input id="payment-value" name="payment-value">
    	</div>
    
    	<div id="paymeny-notes">
    		<h3>Комментарий</h3>
    		<input id="payment-notes" size="50" name="payment-notes">
    	</div>
    </div>
    <input id="form-submit" type="submit">
	<input type="hidden" name="option" value="com_oms2" />
	<input type="hidden" name="view" value="addpay" />
	<?php echo JHTML::_('form.token'); ?>

</form>