<?php
/**
 * @version		1.0.0 oms2 $
 * @package		oms2
 * @copyright	Copyright © 2013 - All rights reserved.
 * @license		GNU/GPL
 * @author		Andrey Shlyapin
 * @author mail	andrey@skzd.ru
 * @website		http://www.pokupaem-v-amerike.com/
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

jimport( 'joomla.application.component.model' );

class oms2ModelOms2 extends Jmodel
{
	private $user;
	public $update_status=false;
	
	function __construct(){
		$this->user = JFactory::getUser();
		parent::__construct();
	}
	
	function getOrder()
	{
		$order = $this->getTable('Orders');
		$order->load(JRequest::getCMD('id'));
		$order->total=round($order->price*$order->amount*(1+$order->tax/100)*(1+$order->interest/100)*$order->currency_rate,2);
		return $order;
	}
	
	function  getHistory(){
		$query 	= 'SELECT *'
				. ' FROM ' . $this->_db->nameQuote('#__ordermanagementsystem_status_history')
				. ' WHERE `order` = '.JRequest::getCMD('id')
				. ' ORDER BY date';
		$this->_db->setQuery($query);
		return $this->_db->loadObjectList();
	}

	function paymentConfirm()
	{
		$id=JRequest::getCmd('id');
		$this->row = $this->getTable('payments');
		$this->row->load($id);
		$this->row->status=1;
		return $this->save();
	}
		
	function getOmsUser(){
		$o = new stdclass;
		$o->user=$this->user;
		$o->orders=$this->getOrders();
		$o->ordersSum=round($this->getOrdersCosts(),2);
		$o->paymentsByStatus=$this->getPaymentsByStatus();
		return $o;
	}
	
	function getOmsUserOrders(){
		$o=$this->getOmsUser();
		$o->orders=$this->getOrders();
		return $o;
	}
	
	function getOmsUserPayments(){
		$o=$this->getOmsUser();
		$o->payments=$this->getPayments();
		return $o;
	}
	
	function  getOrders(){
		$query 	= 'SELECT *'
				. ' FROM ' . $this->_db->nameQuote('#__ordermanagementsystem')
				. ' WHERE `user_id` = '.$this->user->id
				. ' ORDER BY id';
		$this->_db->setQuery($query);
		return $this->_db->loadObjectList();
	}
	
	function getPayments(){
		$query 	= 'SELECT *'
				. ' FROM ' . $this->_db->nameQuote('#__ordermanagementsystem_payments')
				. ' WHERE `user_id` = '.$this->user->id
				. ' ORDER BY id';
		$this->_db->setQuery($query);
		return $this->_db->loadObjectList();
	}
	
	function getOrdersCosts(){
		$query 	= 'SELECT sum(price*amount*(1+tax/100)*(1+interest/100)*currency_rate) as ordersSum'
				. ' FROM ' . $this->_db->nameQuote('#__ordermanagementsystem')
				. ' WHERE `user_id` = '.$this->user->id
				. ' ORDER BY id';
		$this->_db->setQuery($query);
		$orders=$this->_db->loadObjectList();
		return $orders[0]->ordersSum;
	}
	
	function getInsertId(){
		return $this->_db->insertid();
	}
	
	function getPaymentsByStatus(){
		$query 	= 'SELECT status, sum(value) as paymentsSum'
				. ' FROM ' . $this->_db->nameQuote('#__ordermanagementsystem_payments')
				. ' WHERE `user_id` = '.$this->user->id
				. ' GROUP BY status';
		$this->_db->setQuery($query);
		$paiments=$this->_db->loadObjectList();
		$paymentsByStatus[0]=0;
		$paymentsByStatus[1]=0;
		foreach ($this->_db->loadObjectList() as $key){
			$paymentsByStatus[$key->status]=$key->paymentsSum;
		}
		return $paymentsByStatus;
	}
	
	function addOrder() {
		$data = JRequest::get('post');
		$data['order-site']=preg_replace('/http:\/\/anonymouse.org\/cgi-bin\/anon-www.cgi/', '', $data['order-url']);
		preg_match('/:\/\/([a-z0-9\.]+)\//i',$data['order-site'],$matches);
		$this->row = $this->getTable('Orders');
		$this->row->item=$data['order-item'];
		$this->row->item_url=$data['order-url'];
		$this->row->article=$data['order-article'];
		$this->row->size=$data['order-size'];
		$this->row->color=$data['order-color'];
		$this->row->amount=$data['order-amount'];
		$this->row->price=str_replace(',','.',$data['order-price']);
		$this->row->currency=$data['order-currency'];
		$this->row->notes=$data['order-notes'];
		$this->row->user_id=$this->user->id;
		$this->row->site=$matches[1];
		$this->row->currency_rate=str_replace(',','.',$this->getCurrencyRate($this->row->currency));
		return $this->save();
	}
	
	function saveOrder() {
		$data = JRequest::get('post');
		$data['order-site']=preg_replace('/http:\/\/anonymouse.org\/cgi-bin\/anon-www.cgi/', '', $data['order-url']);
		preg_match('/:\/\/([a-z0-9\._-]+)\//i',$data['order-site'],$matches);
		$this->row = $this->getTable('Orders');
		$this->row->load($data['id']);
		
		if ($this->row->status != $data['order-status']){
			$this->update_status=true;
		}
		
		$this->row->status=$data['order-status'];
		$this->row->item=$data['order-item'];
		$this->row->item_url=$data['order-url'];
		$this->row->article=$data['order-article'];
		$this->row->size=$data['order-size'];
		$this->row->color=$data['order-color'];
		$this->row->amount=$data['order-amount'];
		$this->row->price=str_replace(',','.',$data['order-price']);
		$this->row->currency=$data['order-currency'];
		$this->row->notes=$data['order-notes'];
		$this->row->user_id=$this->user->id;
		$this->row->site=$matches[1];
		$this->row->currency_rate=str_replace(',','.',$data['order-currency-rate']);
		$this->row->tax=str_replace(',','.',$data['order-tax']);
		$this->row->interest=str_replace(',','.',$data['order-interest']);
		return $this->save();
	}
	
	
	
	function getCurrencyRate($currency='USD'){
		$rate = $this->getTable('Currency');
		$rate->load($currency);
		return $rate->rate;
	}
	
	
	function addPay() {
		$data = JRequest::get('post');
		$this->row = $this->getTable('Payments');
		$this->row->payment_date=$data['payment_date'];
		$this->row->value=$data['payment-value'];
		$this->row->notes=$data['payment-notes'];
		$this->row->user_id=$this->user->id;
		return $this->save();
	}
	
	function save(){
		if ($this->row->check())
		{
			if (!$this->row->store())
			{
				$this->setError($this->row->getError());
				return JText::_('SAVE FAILED');
			}
		}
		else
		{
			$this->setError($this->row->getError());
			return JText::_('SAVE FAILED');
		}
		return JText::_('SAVE OK');
	}
	
	
	function addHistory($id,$status=FALSE) {
		$this->row = $this->getTable('History');
		if ($status) $this->row->status=$status;
		$this->row->order=$id;
		return $this->save();
	}
	
	
	
	
	
}
?>