<?php
/**
 * @version		1.0.0 oms2 $
 * @package		oms2
 * @copyright	Copyright © 2013 - All rights reserved.
 * @license		GNU/GPL
 * @author		Andrey Shlyapin
 * @author mail	andrey@skzd.ru
 * @website		http://www.pokupaem-v-amerike.com/
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

jimport( 'joomla.application.component.model' );

class oms2ModelOms2 extends Jmodel
{
	function __construct(){
		parent::__construct();
	}
	
	public function getOrders()
	{
		
		$query 	= 'SELECT id,time,item,site,item_url,status'
				. ' FROM ' . $this->_db->nameQuote('#__ordermanagementsystem')
				#. ' WHERE `user_id` = '.$user->id
				. ' ORDER BY id';
		$this->_db->setQuery($query);
		return  $this->_db->loadObjectList();
	}



}
?>